### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by afolson** [afolson/volturnus#1]
Here is a list of TODO items.
## 2.0 Release
- [ ] Convert templates to Twig
- [ ] Reconsider DB schema/CRUDing in general
- [ ] Persistent bot connection to receive rehash signals?
- [ ] Add feature to store/list server numerics

**Comment by Alauraa** [comment]
Is this project dead, or is there a new IRC i could go to, to talk about this project?

**Comment by afolson** [comment]
I'm still around but I don't admin any IRC networks anymore so it was never updated. What are you looking to do?

**Comment by Alauraa** [comment]
I've been rather interested in all the websites that offer control panels for inspircd or unreal and i was wanting to know if this still works on say Php 7.4 and mysql 8 and or mariadb and nginx and what not, Or if it somehow would break if i tried to use newer software for it, that and i was wondering if there was ever going to be a new IRC net for this project?

**Comment by afolson** [comment]
This was written for PHP4/5 so it probably uses some stuff that doesn't exist anymore. I've never tried to run it on PHP 7 so I can't say for sure. I don't really admin any networks now so there likely won't be another network for it -- there isn't really a need to run an IRC network just for this project :P

**Comment by afolson** [comment]
I'm actually going to go ahead and close out this issue, but feel free to open another one if you find any bugs or anything.
